minidlna:
  image: pataquets/minidlna
  command: -d -i eth0
  container_name: minidlna
  restart: unless-stopped
  net: host
  volumes:
    - $HOME/Music/:/var/lib/minidlna/Music:ro
    - $HOME/Pictures/:/var/lib/minidlna/Pictures/:ro
    - $HOME/Videos/:/var/lib/minidlna/Video/:ro
